# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-06-09T10:49:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import ConfigDict, Field, BaseModel


class RootMobileVerifierMobile(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    contact_id: Optional[str] = Field(None, title='Mobile Number')
    otp: Optional[str] = Field(None, title='OTP')
    transaction_id: Optional[str] = Field(None, title='Transaction ID')


class RootMobileVerifier(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    mobile: Optional[RootMobileVerifierMobile] = Field(
        None, description='Enter mobile', title='mobile'
    )


class Sampleform(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    mobile_verifier: Optional[RootMobileVerifier] = Field(
        None, description='This is a mobile info pane.', title='Mobile Info'
    )
